CREATE TABLE IF NOT EXISTS url_redirection_info
(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ip VARCHAR(255) NOT NULL,
    os VARCHAR(100) NOT NULL DEFAULT '',
    platform VARCHAR(100) NOT NULL DEFAULT '',
    browser VARCHAR(100) NOT NULL DEFAULT '',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
)